repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.6
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: run unit tests
        entry: pytest --suppress-no-test-exit-code
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false