openapi: 3.0.2
info:
  description: "Playing Around API"
  version: "0.1"
  title: "Nonsense API"
  contact : 
    responsibleOrganization: Martin Lujan
    responsibleDeveloper: Martin Lujan
    email: lujanmartin91@gmail.com
    
consumes: "application/x-www-form-urlencoded"
produces: "application/json"
  

components:
  securitySchemes:
    basicAuth:     
      type: http
      scheme: basic
  
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    New_Task:
      title: New Task
      type: object
      properties:
        done:
          type: boolean
          description: State of the task
        description:
          type: string
          description: Description of the task
        title:
          type: string
          description: Title of the task
      required:
        - done
        - title
        - description

    Update_Task:
      title: Update Task
      type: object
      properties:
        _id:
          type: string
          description: Id of the task 
        done:
          type: boolean
          description: State of the task 
        description:
          type: string
          description: Description of the task
        title:
          type: string
          description: Title of the task
      required:
        - _id
        - done
      optional:
        - description
        - title

    Delete_Task:
      title: Delete Task
      type : object
      properties:
        _id:
          type: integer
          description: Id of the task
      required:
        - _id 

  examples:
    new_task:
      value:
        done: false
        title: Supermarket
        description: Get milk

    update_task:
      value:
        id: 10
        done: false
        title: Supermarket
        description: Get milk

    delete_task:
      value:
        id: 10

    id_not_found:
      error: Id not found


paths:
  /todo/api/v0.1/tasks/token:
    get:
      summary: Get JWT for authentication
      tags:
      - Token
      security:
        - basicAuth: []
      responses:
        200:
          description: Successfully Authenticated
          content:
            application/json:
              example:
                token : eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1OTE0NTQ2NzYuNTg3ODkyNX0.hYQuXuojy_kEm1jPcal1pCL0lJybF6uqCaVRFntvNWwbk6cIDW2Q1ytBkz7hSZPZSPk897KijKxsTuTze5fS7s6vyDuG5X0gWhXuMzv_yNwEtXP2BwpUvDj24tnHzOjkBrQ2_xIe7dJ2EwX8MnNIss0HRU_1u1tkuj8nZvpLQhI_yjGnGItYv828creZgBZzCwYtY89iHfgJWb34yNdmCFpVN5rGVdp4aOnVdyjYvgbrMh67Z3Ku7_j1QWdbyk2cqpQlATEb3BYnPzbpinR4-e-agbrBwl1A8Sq1FArpSt3kPe2tIT7kkGGG-pxuIDW3B5pz9ZXDkKKb7YUQOWgY-pWMD2OCSj2BowaX0lOFR5jT3mSA6ABJYBTtj1NXRO2Tsed9DtIiBWkNrTHV_xDE00BdCN_td6o-xfsGK_U0A5u0d6AY18KPd_0AMpTC0Kg2K_FcUzid2yraAf4s5gkdaeuT_rugxmK6ikFqDKFpLxW4bmB1owjGOynxs6Z7Kw1fF1aPM1gEpoHqzUBbVGmXVFScy-GlHFfv045KZLUeVFrg3CkXOeT72FWLcmmHl4IxhbT0NhkrLmq-0sWIzRZI9tXYHBgsR-bRtlNEO0OTL9nfhNgn5VhiqVC5OPN1M26SBJ0xXSkGVS2W343CivpxonkUa0zjuUBvEwBQ62UqJ58
        401:
          description: Unauthorized 
          content:
            text/plain:
              example: Unauthorized Access

  
  /todo/api/v0.1/tasks:
    get:
      summary: Get a list of all the tasks
      tags:
        - Tasks
      security:
        - Bearer: []
      responses:
        200:
          description: OK 
    post:
      summary: Add a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/New_Task'
            examples:
              New Task:
                $ref: '#/components/examples/new_task'
      security:
        - Bearer: []
      responses:
        201:
          description: Task Created Successfully
        400:
          description: Bad Request
    put:
      summary: Update a task 
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update_Task'
            examples:
              Update Task:
                $ref: '#/components/examples/update_task'
      security:
        - Bearer: []
      responses:
        200:
          description: OK 
    delete:
      summary: Delete a task by ID
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Delete_Task'
            examples:
              Delete Task:
                $ref: '#/components/examples/delete_task'
      security:
        - Bearer: []
      responses:
        200:
          description: Task Deleted Successfully
        400:
          description : Bad Request

  /todo/api/v0.1/tasks/{_id}:
    get:
      summary: Get a task by ID
      parameters:
        - in: path
          name: _id
          schema:
            type: string
          required: true
          description: ID of the task to get
      tags:
        - Tasks
      security:
        - Bearer: []
      responses:
        200:
          description: OK 
        400:
          description: Bad Request
          content:
            application/json:
              example:
                error: Id not found


